-- ═══════════════════════════════════════════════════════════════
-- NEXUS GAMING CHAT - Script de Configuración de Base de Datos
-- Ejecuta este script en el Editor SQL de tu proyecto Supabase:
-- Dashboard → SQL Editor → Nuevo Query → Pegar y ejecutar
-- ═══════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────
-- 1. TABLA DE CANALES
-- ─────────────────────────────────────────────────────────────
create table if not exists channels (
  id text primary key,
  name text not null,
  type text not null check (type in ('text', 'voice')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Canales por defecto iniciales
insert into channels (id, name, type) values
  ('general', 'general', 'text'),
  ('lounge', 'lounge', 'text'),
  ('clips-and-memes', 'clips-and-memes', 'text'),
  ('estrategia', 'estrategia', 'text'),
  ('general-voice', 'General Voice', 'voice'),
  ('squad-1', 'Squad Alpha', 'voice')
on conflict (id) do nothing;

-- ─────────────────────────────────────────────────────────────
-- 2. TABLA DE MENSAJES
-- ─────────────────────────────────────────────────────────────
create table if not exists messages (
  id bigint generated by default as identity primary key,
  channel_id text references channels(id) on delete cascade not null,
  author text not null,
  avatar text,
  avatar_bg text,
  image text,
  file jsonb,
  text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ─────────────────────────────────────────────────────────────
-- 3. HABILITAR REALTIME EN LA TABLA MESSAGES
-- ─────────────────────────────────────────────────────────────
alter publication supabase_realtime add table messages;

-- ─────────────────────────────────────────────────────────────
-- 4. ROW LEVEL SECURITY (RLS) - Acceso público (sin autenticación)
-- Esto permite leer y escribir mensajes sin login de Supabase.
-- En producción podrías querer restringirlo más.
-- ─────────────────────────────────────────────────────────────

-- Habilitar RLS en channels
alter table channels enable row level security;
create policy "Todos pueden leer canales" on channels
  for select using (true);

-- Habilitar RLS en messages
alter table messages enable row level security;
create policy "Todos pueden leer mensajes" on messages
  for select using (true);
create policy "Todos pueden insertar mensajes" on messages
  for insert with check (true);

-- ─────────────────────────────────────────────────────────────
-- 5. ÍNDICES PARA RENDIMIENTO ÓPTIMO
-- ─────────────────────────────────────────────────────────────
create index if not exists messages_channel_id_idx on messages(channel_id);
create index if not exists messages_created_at_idx on messages(created_at);

-- ─────────────────────────────────────────────────────────────
-- 6. MODIFICACIONES PARA MÚLTIPLES SERVIDORES
-- ─────────────────────────────────────────────────────────────

-- Crear tabla de servidores
create table if not exists servers (
  id text primary key,
  name text not null,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar servidor por defecto inicial
insert into servers (id, name, icon) values
  ('nexus-default', 'Nexus Global', '🌌')
on conflict (id) do nothing;

-- Añadir columna server_id a la tabla de canales
alter table channels add column if not exists server_id text references servers(id) on delete cascade;

-- Asignar los canales existentes al servidor por defecto
update channels set server_id = 'nexus-default' where server_id is null;

-- Habilitar RLS en la tabla servers
alter table servers enable row level security;
create policy "Todos pueden leer servidores" on servers
  for select using (true);
create policy "Todos pueden insertar servidores" on servers
  for insert with check (true);

-- Agregar políticas de inserción y eliminación para canales
create policy "Todos pueden insertar canales" on channels
  for insert with check (true);
create policy "Todos pueden eliminar canales" on channels
  for delete using (true);
