-- ═══════════════════════════════════════════════════════════════
-- NEXUS GAMING CHAT - Script de Configuración de Base de Datos
-- Ejecuta este script en el Editor SQL de tu proyecto Supabase:
-- Dashboard → SQL Editor → Nuevo Query → Pegar y ejecutar
-- ═══════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────
-- 1. TABLA DE SERVIDORES Y DATOS POR DEFECTO
-- ─────────────────────────────────────────────────────────────
create table if not exists servers (
  id text primary key,
  name text not null,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar servidor por defecto inicial
insert into servers (id, name, icon) values
  ('nexus-default', 'Nexus Global', '🌌')
on conflict (id) do nothing;

-- ─────────────────────────────────────────────────────────────
-- 2. TABLA DE CANALES Y DATOS POR DEFECTO
-- ─────────────────────────────────────────────────────────────
create table if not exists channels (
  id text primary key,
  name text not null,
  type text not null check (type in ('text', 'voice')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Añadir columna server_id a la tabla de canales (relación con servidores)
alter table channels add column if not exists server_id text references servers(id) on delete cascade;

-- Asignar los canales existentes/huérfanos al servidor por defecto
update channels set server_id = 'nexus-default' where server_id is null;

-- Canales por defecto iniciales
insert into channels (id, name, type, server_id) values
  ('general', 'general', 'text', 'nexus-default'),
  ('lounge', 'lounge', 'text', 'nexus-default'),
  ('clips-and-memes', 'clips-and-memes', 'text', 'nexus-default'),
  ('estrategia', 'estrategia', 'text', 'nexus-default'),
  ('general-voice', 'General Voice', 'voice', 'nexus-default'),
  ('squad-1', 'Squad Alpha', 'voice', 'nexus-default')
on conflict (id) do nothing;

-- ─────────────────────────────────────────────────────────────
-- 3. TABLA DE MENSAJES
-- ─────────────────────────────────────────────────────────────
create table if not exists messages (
  id bigint generated by default as identity primary key,
  channel_id text references channels(id) on delete cascade not null,
  author text not null,
  avatar text,
  avatar_bg text,
  image text,
  file jsonb,
  text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ─────────────────────────────────────────────────────────────
-- 4. HABILITAR REALTIME (TIEMPO REAL)
-- ─────────────────────────────────────────────────────────────
-- Nota: Hacemos un bloque seguro para evitar errores si ya están añadidas
do $$
begin
  -- Intentar añadir tablas a la publicación de realtime
  begin
    alter publication supabase_realtime add table messages;
  exception when others then null;
  end;
  
  begin
    alter publication supabase_realtime add table servers;
  exception when others then null;
  end;

  begin
    alter publication supabase_realtime add table channels;
  exception when others then null;
  end;
end $$;

-- ─────────────────────────────────────────────────────────────
-- 5. ROW LEVEL SECURITY (RLS) & POLÍTICAS
-- Esto permite el funcionamiento del chat público sin auth restrictiva
-- ─────────────────────────────────────────────────────────────

-- --- Habilitar RLS ---
alter table servers enable row level security;
alter table channels enable row level security;
alter table messages enable row level security;

-- --- Limpiar políticas previas para evitar conflictos de duplicación ---
drop policy if exists "Todos pueden leer servidores" on servers;
drop policy if exists "Todos pueden insertar servidores" on servers;
drop policy if exists "Todos pueden eliminar servidores" on servers;

drop policy if exists "Todos pueden leer canales" on channels;
drop policy if exists "Todos pueden insertar canales" on channels;
drop policy if exists "Todos pueden eliminar canales" on channels;

drop policy if exists "Todos pueden leer mensajes" on messages;
drop policy if exists "Todos pueden insertar mensajes" on messages;
drop policy if exists "Todos pueden eliminar mensajes" on messages;

-- --- Crear políticas limpias para Servidores ---
create policy "Todos pueden leer servidores" on servers for select using (true);
create policy "Todos pueden insertar servidores" on servers for insert with check (true);
create policy "Todos pueden eliminar servidores" on servers for delete using (true);

-- --- Crear políticas limpias para Canales ---
create policy "Todos pueden leer canales" on channels for select using (true);
create policy "Todos pueden insertar canales" on channels for insert with check (true);
create policy "Todos pueden eliminar canales" on channels for delete using (true);

-- --- Crear políticas limpias para Mensajes ---
create policy "Todos pueden leer mensajes" on messages for select using (true);
create policy "Todos pueden insertar mensajes" on messages for insert with check (true);
create policy "Todos pueden eliminar mensajes" on messages for delete using (true);

-- ─────────────────────────────────────────────────────────────
-- 6. ÍNDICES DE RENDIMIENTO
-- ─────────────────────────────────────────────────────────────
create index if not exists messages_channel_id_idx on messages(channel_id);
create index if not exists messages_created_at_idx on messages(created_at);

-- ─────────────────────────────────────────────────────────────
-- 7. TABLA DE PERFILES DE USUARIO (OPCIONAL / RECOMENDADO)
-- Permite búsqueda global persistente de usuarios para el DM Hub
-- ─────────────────────────────────────────────────────────────
create table if not exists profiles (
  email text primary key,
  username text not null,
  avatar text,
  status text default 'offline',
  last_seen timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;
drop policy if exists "Todos pueden leer perfiles" on profiles;
drop policy if exists "Todos pueden upsert su perfil" on profiles;
create policy "Todos pueden leer perfiles" on profiles for select using (true);
create policy "Todos pueden upsert su perfil" on profiles for all using (true);

-- ─────────────────────────────────────────────────────────────
-- 8. TABLA DE MENSAJES DIRECTOS PERSISTENTES (HISTORIAL)
-- ─────────────────────────────────────────────────────────────
create table if not exists direct_messages (
  id bigint generated by default as identity primary key,
  conv_id text not null,
  sender_email text not null,
  sender_name text not null,
  recipient_email text not null,
  text text not null,
  reply_to jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists dm_conv_id_idx on direct_messages(conv_id);
create index if not exists dm_recipient_idx on direct_messages(recipient_email);

alter table direct_messages enable row level security;
drop policy if exists "Todos pueden leer DMs" on direct_messages;
drop policy if exists "Todos pueden insertar DMs" on direct_messages;
create policy "Todos pueden leer DMs" on direct_messages for select using (true);
create policy "Todos pueden insertar DMs" on direct_messages for insert with check (true);
